name: Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
  

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Navigate to Project Directory
      run: cd codeReview/mavenproject1/

    - name: Generate Javadoc
      run: mvn clean javadoc:javadoc

    - name: Deploy to GH-Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./target/site/apidocs
        destination_dir: javadoc/3.4.1

    - name: Add CNAME
      run: echo 'blah.com' > target/site/apidocs/CNAME
